/**
 * Used to send message (alarms) from the device to the control.
 */
export interface Messages {
    /**
     * The date+timestamp which identifies the point in time, where the information was generated, including milliseconds.
     *
     * @format date-time
     */
    timestamp: string

    messages: Message[]
}

/**
 * A message is a textual string giving some reasonable information to a message tracking system of the Mail Information System. The group "Messages" implements the messages (errors, alarms, warnings, informations) generated by a piece of mail processing equipment (MPE). The message parameters defined above are the attributes of this group. This group is defined to be a notifylist. When a new message is created, a new element of this notifylist is created. The machine has to store all messages until the message has been successfully handled by the JMS server (as any Notifylist element, this is a general mechanism for Notifylists). The storage timeframe has to be adjustable to project needs, depending on the availability of the MIS role (normally in the range of half an hour up to 3 hours). Associated to the Message Id, there must be a (language dependent) message text, which has a Java-Text like escape character notation (%1, $1) that allows the text assembly with the provided sequence of (string) parameters. Note that the numbers the escape characters start with 1and that string parameters cannot be translated, they will normally be numbers passed as strings. The interpretation is done according to the escape parameters inside the message text. The Text parameter is only displayed if no language dependent message text can be found for a given Id. The general XML mapping of this element is Messages. As this is a NotifylistElement the header will hold a timestamp that indicates when the problem occured.
 */
export interface Message {
    /**
     * An id, identifying the message. With the help of this Id and the language of the end user, the message text is localized.
     * The id must be unique within the context of the machine (Systemname plus SystemInstance) that generated the message.
     *
     * @type integer
     */
    id: number

    /**
     * String parameter identifying the source of the message. If the source is unknown a kind of text "Machine" must be supplied.
     * As a general rule, the definition of the initiator should be aligned with the module identification of the group messages.
     * For example, the unique plant part identification (AKZ) can be very suitable for that purpose.
     * The initiator is a third layer underneath the systemname and systeminstance to identify the source of the error.
     */
    initiator: string

    /**
     * The priority of the Message.
     */
    priority: MessagePriority

    /**
     * Identifies the mode of the message. In the visualization a message may APPEAR, typically if this is an error.
     * If the problem was fixed there is typically a DISAPPEAR message of type information to indicate that the problem has gone.
     */
    state: MessageState

    /**
     * If the message needs to be acknowledged by an operator.
     */
    acknowledge: boolean

    /**
     * English description text as default fault/warning message with possibilities to insert parameters inJava Text-like format
     * with %N or $N syntax for identification of the N-th parameter.
     * Normally the language specific text from the EMPS database will be used instead of this default text.
     */
    text: string

    /**
     * Parameters for the above mentioned text / text referenced by the id.
     */
    parameters?: string[]
}

export enum MessagePriority {
    INFO,
    WARNING,
    ALARM,
    ERROR
}

/**
 * Defines the alarm states.
 * List of values:
 * - NONE: used for events which occur at a specific timestamp
 * - APPEAR / DISAPPEAR: used for events which can appear for a certain time slice.
 */
export enum MessageState {
    NONE,
    APPEAR,
    DISAPPEAR
}
